### ISSUE TITLE
请问模型是否开源？

### ISSUE THREAD

**Issue by csukuangfj** [frankyoujian/Edge-Punct-Casing#1]
请问 onnx 导出的模型是否开源？如果是，应该从哪里去下载呢？

**Comment by frankyoujian** [comment]
@csukuangfj The PR of integrating this model to sherpa-onnx is on the way, will share one pretrained model to K2 community.

**Comment by csukuangfj** [comment]
> @csukuangfj The PR of integrating this model to sherpa-onnx is on the way, will share one pretrained model to K2 community.

Thank you!
