### ISSUE TITLE
Is there any pre-trained model to use for?

### ISSUE THREAD

**Issue by XhrLeokk** [frankyoujian/Edge-Punct-Casing#2]
hello, sir. Maybe need bpe.model & model.pt to run decode.py, right? May u provide a demo file for testing?

**Comment by XhrLeokk** [comment]
sorry, i missed the HF repo,
https://huggingface.co/frankyoujian/Edge-Punct-Casing/tree/main

**Comment by csukuangfj** [comment]
https://k2-fsa.github.io/sherpa/onnx/punctuation/pretrained_models.html#sherpa-onnx-online-punct-en-2024-08-06-english-only
Please also have a look at the above link.

**Comment by frankyoujian** [comment]
@XhrLeokk I have integrated this model to K2 repo, you can refer to [PR to sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx/pull/1224) for deployment.
